### ISSUE TITLE
[BUG] -  Dropdown Item not usable on Android

### ISSUE THREAD

**Issue by stgogm** [nextui-org/nextui#1349]
### Describe the bug

This does nothing when trying to activate a dropdown item on an Android device. I've tested with 2 different devices. Using the Chrome remote debugger I can activate the item if I click on it on my computer, but tapping on the device does nothing.

Tapping on the tabs does nothing either.

### Your Example Website or App

https://nextui.org/docs/components/dropdown#usage

### Steps to Reproduce the Bug or Issue

1. Using Chrome on an Android device, go to https://nextui.org/docs/components/dropdown#usage
3. Tap the dropdown trigger
4. Tap an item
5. Nothing happens

### Expected behavior

When an item is tapped, it should close the dropdown and trigger the actions.

### Operating System Version

Android

### Browser

Chrome

**Comment by jguddas** [comment]
Work's on my machine.

Chrome 115.0.5790.139  
Android 13

**Comment by jrgarciadev** [comment]
Hey @stgogm are you using a real device, or are you using the one provided by Chrome Dev Tools?

**Comment by stgogm** [comment]
Thanks for revising this.

I tried with two real devices, and one definitively doesn't work. There are no error logs or anything:

https://github.com/nextui-org/nextui/assets/2774311/873c3637-3763-422f-9702-8e16ca7502f3

I've tried other libraries (MUI, Prime), and they work well, so I'm trying to figure out what's happening.

#### Not working device:
- Redmi Note 10 Pro
- Android 13 TKQ1.221013.002
- MIUI Global 14.0.2.0
- Chrome 115.0.5790.166

**Comment by jguddas** [comment]
https://github.com/adobe/react-spectrum/issues/3945

**Comment by dmythro** [comment]
I had issues with Dropdown wrapped in a Tooltip. Also, Dropdown or Popover doesn't work for me in Chrome's responsive tool (but it works fine on actual devices as I checked), Chrome is v115 latest. Example: [my webpage](https://dmythro.com/) (there are sources as well, link in footer), plan to replace with something else, noticed after it was already there.

**Comment by dmythro** [comment]
Yeah, also doesn't work on my test Android 13 (Pixel 4a). Only Navbar toggle works from this kind of controls (visible only on small screens via link above).

**Comment by jrgarciadev** [comment]
> I had issues with Dropdown wrapped in a Tooltip. Also, Dropdown or Popover doesn't work for me in Chrome's responsive tool (but it works fine on actual devices as I checked, works fine in Safari and it's responsive design tool, works in iOS 16), Chrome is v115 latest. Example: [my webpage](https://dmythro.com/) (there are sources as well, link in footer), plan to replace with something else as it may not work in some edge cases, noticed after it was already there.

For issues regarding Tooltip wrapping other overlays components please check this https://github.com/nextui-org/nextui/issues/1265

**Comment by dmythro** [comment]
> For issues regarding Tooltip wrapping other overlays components please check this https://github.com/nextui-org/nextui/issues/1265

Thanks! Yes, I had figured out that kind of a workaround, but then decided to rework layout a bit :)

**Comment by devongovett** [comment]
Could you please go to this page on your device, tap the button, and paste the output you get? Also please include as much info as possible about your device, including hardware, Android version, Chrome version, etc. https://codepen.io/devongovett/pen/XWyLEvy

**Comment by emmanuelxd** [comment]
> Could you please go to this page on your device, tap the button, and paste the output you get? Also please include as much info as possible about your device, including hardware, Android version, Chrome version, etc. https://codepen.io/devongovett/pen/XWyLEvy

{
  "isTrusted": true,
  "pointerId": 2,
  "width": 0,
  "height": 0,
  "pressure": 1,
  "tiltX": 0,
  "tiltY": 0,
  "azimuthAngle": 0,
  "altitudeAngle": 1.5707963267948966,
  "tangentialPressure": 0,
  "twist": 0,
  "pointerType": "touch",
  "isPrimary": true,
  "screenX": 63.6363639831543,
  "screenY": 498.18182373046875,
  "clientX": 63.6363639831543,
  "clientY": 18.636363983154297,
  "ctrlKey": false,
  "shiftKey": false,
  "altKey": false,
  "metaKey": false,
  "button": 0,
  "buttons": 1,
  "pageX": 63.6363639831543,
  "pageY": 18.636363983154297,
  "x": 63.6363639831543,
  "y": 18.636363983154297,
  "offsetX": 53.81818389892578,
  "offsetY": 8.818181991577148,
  "movementX": 0,
  "movementY": 0,
  "layerX": 63,
  "layerY": 18,
  "detail": 0,
  "which": 1,
  "type": "pointerdown",
  "eventPhase": 2,
  "bubbles": true,
  "cancelable": true,
  "defaultPrevented": false,
  "composed": true,
  "timeStamp": 3435.5,
  "returnValue": true,
  "cancelBubble": false,
  "NONE": 0,
  "CAPTURING_PHASE": 1,
  "AT_TARGET": 2,
  "BUBBLING_PHASE": 3
}

**Comment by emmanuelxd** [comment]
> Could you please go to this page on your device, tap the button, and paste the output you get? Also please include as much info as possible about your device, including hardware, Android version, Chrome version, etc. https://codepen.io/devongovett/pen/XWyLEvy

{
  "isTrusted": true,
  "pointerId": 2,
  "width": 0,
  "height": 0,
  "pressure": 1,
  "tiltX": 0,
  "tiltY": 0,
  "azimuthAngle": 0,
  "altitudeAngle": 1.5707963267948966,
  "tangentialPressure": 0,
  "twist": 0,
  "pointerType": "touch",
  "isPrimary": true,
  "screenX": 63.6363639831543,
  "screenY": 498.18182373046875,
  "clientX": 63.6363639831543,
  "clientY": 18.636363983154297,
  "ctrlKey": false,
  "shiftKey": false,
  "altKey": false,
  "metaKey": false,
  "button": 0,
  "buttons": 1,
  "pageX": 63.6363639831543,
  "pageY": 18.636363983154297,
  "x": 63.6363639831543,
  "y": 18.636363983154297,
  "offsetX": 53.81818389892578,
  "offsetY": 8.818181991577148,
  "movementX": 0,
  "movementY": 0,
  "layerX": 63,
  "layerY": 18,
  "detail": 0,
  "which": 1,
  "type": "pointerdown",
  "eventPhase": 2,
  "bubbles": true,
  "cancelable": true,
  "defaultPrevented": false,
  "composed": true,
  "timeStamp": 3435.5,
  "returnValue": true,
  "cancelBubble": false,
  "NONE": 0,
  "CAPTURING_PHASE": 1,
  "AT_TARGET": 2,
  "BUBBLING_PHASE": 3
}

**Comment by stgogm** [comment]
@devongovett this is on the non working device:

```
{
  "isTrusted": true,
  "pointerId": 7,
  "width": 0,
  "height": 0,
  "pressure": 1,
  "tiltX": 0,
  "tiltY": 0,
  "azimuthAngle": 0,
  "altitudeAngle": 1.5707963267948966,
  "tangentialPressure": 0,
  "twist": 0,
  "pointerType": "touch",
  "isPrimary": true,
  "screenX": 21.090909957885742,
  "screenY": 492,
  "clientX": 22.936052322387695,
  "clientY": 24.672319412231445,
  "ctrlKey": false,
  "shiftKey": false,
  "altKey": false,
  "metaKey": false,
  "button": 0,
  "buttons": 1,
  "pageX": 22.936052322387695,
  "pageY": 24.672319412231445,
  "x": 22.936052322387695,
  "y": 24.672319412231445,
  "offsetX": 12.96331787109375,
  "offsetY": 14.6995849609375,
  "movementX": 0,
  "movementY": 0,
  "layerX": 22,
  "layerY": 24,
  "detail": 0,
  "which": 1,
  "type": "pointerdown",
  "eventPhase": 2,
  "bubbles": true,
  "cancelable": true,
  "defaultPrevented": false,
  "composed": true,
  "timeStamp": 9183.899999976158,
  "returnValue": true,
  "cancelBubble": false,
  "NONE": 0,
  "CAPTURING_PHASE": 1,
  "AT_TARGET": 2,
  "BUBBLING_PHASE": 3
}
```

**Comment by jguddas** [comment]
This is from a working device, as you can see `height` and `width` are not `0`.
```{ "isTrusted": true, "pointerId": 19, "width": 2.6666667461395264, "height": 2.6666667461395264, "pressure": 1, "tiltX": 0, "tiltY": 0, "azimuthAngle": 0, "altitudeAngle": 1.5707963267948966, "tangentialPressure": 0, "twist": 0, "pointerType": "touch", "isPrimary": true, "screenX": 41.29166793823242, "screenY": 455.41668701171875, "clientX": 41.29166793823242, "clientY": 20.08333396911621, "ctrlKey": false, "shiftKey": false, "altKey": false, "metaKey": false, "button": 0, "buttons": 1, "pageX": 41.29166793823242, "pageY": 20.08333396911621, "x": 41.29166793823242, "y": 20.08333396911621, "offsetX": 31.291667938232422, "offsetY": 10.083333969116211, "movementX": 0, "movementY": 0, "layerX": 41, "layerY": 20, "detail": 0, "which": 1, "type": "pointerdown", "eventPhase": 2, "bubbles": true, "cancelable": true, "defaultPrevented": false, "composed": true, "timeStamp": 12066.699999809265, "returnValue": true, "cancelBubble": false, "NONE": 0, "CAPTURING_PHASE": 1, "AT_TARGET": 2, "BUBBLING_PHASE": 3 }```

**Comment by dmythro** [comment]
So, for now as a workaround I've noticed that drop-downs without backdrop work for me on all devices, so removed it.
Looks way cooler with a blurred backdrop, but it's much more important to have it working for now :)

**Comment by devongovett** [comment]
@emmanuelxd @stgogm thanks! could you repeat the same thing except click the button using Android's TalkBack screen reader? That's what we're trying to detect here. See [here](https://support.google.com/accessibility/android/answer/6007100?hl=en) for how to turn TalkBack on and off (usually you press and hold both volume buttons). Once it is on, move the virtual cursor to the button and double tap to click.

**Comment by emmanuelxd** [comment]
@devongovett sure!

Results with TalkBack **On**


```javascript
{
  "isTrusted": true,
  "pointerId": 1,
  "width": 1,
  "height": 1,
  "pressure": 0,
  "tiltX": 0,
  "tiltY": 0,
  "azimuthAngle": 0,
  "altitudeAngle": 1.5707963267948966,
  "tangentialPressure": 0,
  "twist": 0,
  "pointerType": "mouse",
  "isPrimary": true,
  "screenX": 15,
  "screenY": 148,
  "clientX": 41,
  "clientY": 18,
  "ctrlKey": false,
  "shiftKey": false,
  "altKey": false,
  "metaKey": false,
  "button": 0,
  "buttons": 1,
  "pageX": 41,
  "pageY": 18,
  "x": 41,
  "y": 18,
  "offsetX": 0,
  "offsetY": 0,
  "movementX": 0,
  "movementY": 0,
  "layerX": 41,
  "layerY": 18,
  "detail": 0,
  "which": 1,
  "type": "pointerdown",
  "eventPhase": 2,
  "bubbles": true,
  "cancelable": true,
  "defaultPrevented": false,
  "composed": true,
  "timeStamp": 11230,
  "returnValue": true,
  "cancelBubble": false,
  "NONE": 0,
  "CAPTURING_PHASE": 1,
  "AT_TARGET": 2,
  "BUBBLING_PHASE": 3
}
```

**Comment by devongovett** [comment]
Great thanks. We will make some updates on the React Aria side and post a link here for you to test once we have a potential fix. And sorry again, these device specific bugs are hard! 😄

**Comment by yihuiliao** [comment]
Hey everyone! We have a potential fix on the React Aria side so if you were having issues previously, could you please go to [this page](https://reactspectrum.blob.core.windows.net/reactspectrum/c73d2d6b473a7a149b7ef35ea5962b6ae8e2a9a8/docs/react-aria/usePress.html#example) on the docs, scroll to the button that says 'Press me!', and report what it says? Unfortunately, our team doesn't have the devices which are causing this issue so your help would be much appreciated!

**Comment by LFDanLu** [comment]
Just wanted to chime in with the following bug filed against Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1271444. The check we use in React Aria relies on several attributes of the click event, but is still quite brittle especially since Talkback sometimes issues events with `pointerType: touch` and `height/width: 0`. Ideally, attributes like `isPrimary` would be false for a TalkBack click.

**Comment by stgogm** [comment]
@yihuiliao this is what i get:

```
- press start with touch
- press end with touch
- press with touch
```

Thanks!

**Comment by Maadhav** [comment]
Is there anyway to fix this issue temporarily? A lot of our users are mobile based and hence a lot of them are getting this issue.

**Comment by emmanuelxd** [comment]
@yihuiliao


```
- press start with touch
- press end with touch
- press with touch
``` 

`Android 12 SKQ1.211006.001
Chrome versión 115.0.5790.166
MIUI 13.0.3`

**Comment by LucasTrombim** [comment]
Is there anyway to fix this issue temporarily? A lot of users are having this issue.

**Comment by jguddas** [comment]
Has anyone tried to see if the changes that are not yet released in react-aria fixes all of this?

**Comment by LucasTrombim** [comment]
I don't understand, what do you mean? Do I install the react-aria package on the main branch?

**Comment by devongovett** [comment]
You could try using the `nightly` version of `@react-aria/interactions` by using npm overrides/yarn resolutions.

```json
{
  "overrides": {
    "@react-aria/interactions": "nightly"
  }
}
```

**Comment by LucasTrombim** [comment]
I'll try it out and get back to you with the results!

**Comment by devongovett** [comment]
@LucasTrombim if you go to the link posted by @yihuiliao above and click the button what do you see?

**Comment by LucasTrombim** [comment]
> @LucasTrombim if you go to the link posted by @yihuiliao above and click the button what do you see?

- press start with touch
- press end with touch
- press with touch

**Comment by devongovett** [comment]
That seems correct. Can you verify what version(s) of `@react-aria/interactions` are in your node_modules? Make sure you don't have multiple as well.

**Comment by LucasTrombim** [comment]
`{
  "dependencies": {
    "@react-aria/visually-hidden": "^3.8.1",
    "next": "13.4.19",
    "@nextui-org/react": "2.0.0"
  },
  "overrides": {
    "react-aria": "3.27.1-nightly.4094"
  },
}
`

**Comment by LucasTrombim** [comment]
`
{
  "dependencies": {
    "@nextui-org/react": "2.0.0",
  },
  "overrides": {
    "@react-aria/interactions": "3.27.1-nightly.4094"
  },
}
`

**Comment by LucasTrombim** [comment]
{
  "dependencies": {
    "@nextui-org/react": "2.0.0",
  },
  "overrides": {
    "@react-aria/interactions": "3.27.1-nightly.4094"
  },
}

**Comment by LucasTrombim** [comment]
```
{
  "dependencies": {
    "@nextui-org/react": "2.0.0",
  },
  "overrides": {
    "@react-aria/interactions": "3.27.1-nightly.4094"
  },
}
```

**Comment by devongovett** [comment]
Yes but can you verify what was actually installed in your node_modules in case the override didn't work for some reason?

**Comment by LucasTrombim** [comment]
installed version 3.16, I'll add it to the main dependencies, and see if it resolves and forces the version

**Comment by LucasTrombim** [comment]
didn't work, any other alternative?

**Comment by LFDanLu** [comment]
what does `npm list @react-aria/interactions` return for you? Perhaps you are running into https://github.com/npm/cli/issues/5850 with the override?

**Comment by LucasTrombim** [comment]
```
├─┬ @nextui-org/react@2.0.0
│ ├─┬ @nextui-org/accordion@2.0.0
│ │ ├─┬ @react-aria/accordion@3.0.0-alpha.19
│ │ │ ├── @react-aria/interactions@3.17.0 deduped
│ │ │ └─┬ @react-aria/selection@3.16.1
│ │ │   └── @react-aria/interactions@3.17.0 deduped
│ │ ├─┬ @react-aria/focus@3.14.0
│ │ │ └── @react-aria/interactions@3.17.0 deduped
│ │ └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/avatar@2.0.0
│ │ └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/button@2.0.0
│ │ ├─┬ @nextui-org/use-aria-button@2.0.0
│ │ │ └── @react-aria/interactions@3.17.0 deduped
│ │ ├─┬ @react-aria/button@3.8.1
│ │ │ └── @react-aria/interactions@3.17.0 deduped
│ │ └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/card@2.0.0
│ │ └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/checkbox@2.0.0
│ │ ├─┬ @react-aria/checkbox@3.10.0
│ │ │ └─┬ @react-aria/toggle@3.7.0
│ │ │   └── @react-aria/interactions@3.17.0 deduped
│ │ └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/chip@2.0.0
│ │ └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/dropdown@2.0.0
│ │ ├── @react-aria/interactions@3.17.0 deduped
│ │ └─┬ @react-aria/menu@3.10.1
│ │   └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/input@2.0.0
│ │ └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/link@2.0.0
│ │ ├─┬ @react-aria/link@3.5.3
│ │ │ └── @react-aria/interactions@3.17.0 deduped
│ │ └─┬ @react-types/link@3.4.4
│ │   └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/modal@2.0.0
│ │ ├── @react-aria/interactions@3.17.0 deduped
│ │ └─┬ @react-aria/overlays@3.16.0
│ │   └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/navbar@2.0.0
│ │ └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/pagination@2.0.0
│ │ └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/popover@2.0.0
│ │ └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/radio@2.0.0
│ │ ├── @react-aria/interactions@3.17.0 deduped
│ │ └─┬ @react-aria/radio@3.7.0
│ │   └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/switch@2.0.0
│ │ └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/table@2.0.0
│ │ ├── @react-aria/interactions@3.17.0 deduped
│ │ └─┬ @react-aria/table@3.11.0
│ │   ├─┬ @react-aria/grid@3.8.1
│ │   │ └── @react-aria/interactions@3.17.0 deduped
│ │   └── @react-aria/interactions@3.17.0 deduped
│ ├─┬ @nextui-org/tabs@2.0.0
│ │ ├── @react-aria/interactions@3.17.0 deduped
│ │ └─┬ @react-aria/tabs@3.6.2
│ │   └── @react-aria/interactions@3.17.0 deduped
│ └─┬ @nextui-org/tooltip@2.0.0
│   ├── @react-aria/interactions@3.17.0 deduped
│   └─┬ @react-aria/tooltip@3.6.1
│     └── @react-aria/interactions@3.17.0 deduped
├── @react-aria/interactions@3.17.0
└─┬ @react-aria/visually-hidden@3.8.3
  └── @react-aria/interactions@3.17.0 deduped
```

**Comment by LFDanLu** [comment]
Can you try pulling and running this locally: https://github.com/LFDanLu/android-test? It has the `@react-aria/interactions` override and works on my Android device (but I never was able to reproduce the original issue). Just try tapping on the "Open Menu" button.

**Comment by LucasTrombim** [comment]
It worked! I'll check package by package to see what the problem might be.

**Comment by LucasTrombim** [comment]
When I tried to fork it, and download it to run on my site. It's not working anymore, what version of node are you using? Can you tell me the problem?

**Comment by LFDanLu** [comment]
I'm on node `16.20` but just tried `18.12.1` locally and the `react-aria/interactions` override still worked with a complete clean install (aka deleted lockfile + node modules). Just to be clear, you forked https://github.com/LFDanLu/android-test and ran that repo locally but the override wasn't applied?

**Comment by LucasTrombim** [comment]
I did a local test and realized that the problem was the installation of the packages with yarn. Even with yarn up to date and working, the component still has the problem. After running the same configurations with npm, it works perfectly. Can you tell me how to solve it?

**Comment by LucasTrombim** [comment]
I found the solution, it was my package.json config.... i was using "overrides" with yarn instead of "resolutions".

**Comment by MisterHims** [comment]
Hi there! For me, using the "backdrop" prop prevents the component from working on mobile: when I tap, no reaction. The phenomenon also occurs with the Dropdown component when the "backdrop" prop is used.

OS: Android 13 - Pixel 6a
Browser: Chrome 116.0.5845.163

**Comment by LFDanLu** [comment]
@MisterHims does it still break if you apply the "backdrop" prop in https://github.com/LFDanLu/android-test/blob/661f4e9e27d9e40361e47f0cdcaf33c6b075498c/app/page.tsx#L13? Curious if this is a separate issue from the erroneous virtual click detection problem.

**Comment by jrgarciadev** [comment]
@MisterHims @LFDanLu are you testing in real devices or are you using the chrome dev tools?

**Comment by LFDanLu** [comment]
@jrgarciadev I'm using a Samsung Galaxy S22+, Android 13, Chrome 116.0.5845.163.

**Comment by MisterHims** [comment]
> @MisterHims does it still break if you apply the "backdrop" prop in https://github.com/LFDanLu/android-test/blob/661f4e9e27d9e40361e47f0cdcaf33c6b075498c/app/page.tsx#L13? Curious if this is a separate issue from the erroneous virtual click detection problem.

Yes, still break with using backdrop="blur" in this case. I also tried with the Microsoft Edge 116.0.1938.64 browser.

**Comment by LFDanLu** [comment]
Curious, what prints out for you when you tap on button in the example [here](https://reactspectrum.blob.core.windows.net/reactspectrum/b7e43c6fcb2f4aa8ec3fa8ec025796706da6c88d/docs/react-aria/usePress.html#example)?

**Comment by OtabekVaxobov** [comment]
> Can you try pulling and running this locally: https://github.com/LFDanLu/android-test? It has the `@react-aria/interactions` override and works on my Android device (but I never was able to reproduce the original issue). Just try tapping on the "Open Menu" button.
> 
> here is a codesandbox link for the above repo: https://codesandbox.io/p/sandbox/github/LFDanLu/android-test/tree/main

thank U, its work

**Comment by MisterHims** [comment]
> Curious, what prints out for you when you tap on button in the example [here](https://reactspectrum.blob.core.windows.net/reactspectrum/b7e43c6fcb2f4aa8ec3fa8ec025796706da6c88d/docs/react-aria/usePress.html#example)?

![Screenshot_20230906-165818.png](https://github.com/nextui-org/nextui/assets/41004451/f6f3756f-4931-4c6b-b319-2049c0d602ca)

**Comment by LFDanLu** [comment]
That looks to be the proper result and would indicate to me that it is more likely that the break with `backdrop="blur"` has to do with something other than the press event detection that we've fixed in react-aria. I'm not familiar with the implementation of the Dropdown component here though, so I can't say for sure.

**Comment by devongovett** [comment]
FYI the fix was released in the latest version! https://react-spectrum.adobe.com/releases/2023-09-07.html

**Comment by KhalidHassan218** [comment]
this issue still exist in the latest verison of nextui , using yarn

**Comment by siyasangab** [comment]
issue still exists

**Comment by LFDanLu** [comment]
@siyasangab @KhalidHassan218 do you have a reproduction I can try? I just tried the [NextUI dropdown](https://nextui.org/docs/components/dropdown#usage) on my Android phone (Chrome 131, Android 14) and it seems to work fine.

**Comment by KhalidHassan218** [comment]
I already got fired , does not matter for me anymore , but for others .... 

I remember that I have fixed using a workaround using use disclosure and worked fine
