### ISSUE TITLE
[BUG] - MODAL ANIMATION 

### ISSUE THREAD

**Issue by PaulStat** [nextui-org/nextui#2391]
### NextUI Version

2.2.9

### Describe the bug

I am expecting this issue when trying to use modal in my Next.js application. this warning appears each time modal popups.
Anyway it works, modal popups, maybe with little flickering... But each time drops this warning in console:
You are trying to animate y from "0px" to "var(--slide-enter))". 0px is not an animatable value - to enable this animation set 0px to a value animatable to var(--slide-enter)) via the style property.
![Screenshot 2024-02-19 150748](https://github.com/nextui-org/nextui/assets/155636462/83e8427f-68d1-40ca-97f9-dc3b3b700e6b)

I found a problem, it is a small bug in library: it is left by mistake double brackets at the end of : y: "var(--slide-enter))",
It is in modal component index.js file. :

### Steps to Reproduce the Bug or Issue

node_modules => @nextui-org => modal => dist => index.js
`var scaleInOut = {
  enter: {
    scale: "var(--scale-enter)",
    y: "var(--slide-enter))",
    opacity: 1,
    transition: {
      scale: {
        duration: 0.4,
        ease: import_framer_transitions.TRANSITION_EASINGS.ease
      },
      opacity: {
        duration: 0.4,
        ease: import_framer_transitions.TRANSITION_EASINGS.ease
      },
      y: {
        type: "spring",
        bounce: 0,
        duration: 0.6
      }
    }
  },
  exit: {
    scale: "var(--scale-exit)",
    y: "var(--slide-exit)",
    opacity: 0,
    transition: {
      duration: 0.3,
      ease: import_framer_transitions.TRANSITION_EASINGS.ease
    }
  }
};`

### Expected behavior

It suppose to be no warning in console and Modal must popup without any flickering. 

### Screenshots or Videos

![Screenshot 2024-02-19 150748](https://github.com/nextui-org/nextui/assets/155636462/fa030881-eb2f-473d-9823-fbd18e789d91)

### Operating System Version

Windows

### Browser

Chrome

**Comment by g-popovic** [comment]
I also received this flickering animation weirdness. It seems that downgrading from `framer-motion` `v11` to `v10` fixed the issue however. Just sharing this as a workaround until it's properly fixed

**Comment by arsallanShahab** [comment]
encountered the same issue "errors.mjs:8  You are trying to animate y from "0px" to "var(--slide-enter))". 0px is not an animatable value - to enable this animation set 0px to a value animatable to var(--slide-enter)) via the `style` property."

**Comment by rsemihkoca** [comment]
i have overriden motion props with this one and seems no error now

                motionProps={{
                    variants: {
                        enter: {
                            y: 0,
                            opacity: 1,
                            transition: {
                                duration: 0.3,
                                ease: "easeOut",
                            },
                        },
                        exit: {
                            y: -20,
                            opacity: 0,
                            transition: {
                                duration: 0.2,
                                ease: "easeIn",
                            }
                        }
                    }
                }}

**Comment by kuri-sun** [comment]
Hello all! this one is fixed by https://github.com/nextui-org/nextui/pull/2426.

**Comment by lexcode1227** [comment]
Just in case some of you are still having that issue, what i do for solving it, was to update the framer motion version to the one more recently and that warning dissapear.
