### ISSUE TITLE
[BUG] - When focusing input field the text of error message is not visible properly

### ISSUE THREAD

**Issue by milad-raza** [nextui-org/nextui#3740]
### NextUI Version

^2.4.6

### Describe the bug

When clicking on the input field while it's displaying the error message the text of error message is not visible properly,
it was visible before focusing.

**Before**
![before](https://github.com/user-attachments/assets/fc1262f4-ea76-4ff8-a165-3f308a52f5f6)

**After**
![after](https://github.com/user-attachments/assets/fab4a043-f74c-4651-a33f-572ee5a69637)

as you can see the difference in second image after focusing, same on next UI web app this is how it's displaying, un-readable text
![unread](https://github.com/user-attachments/assets/0e328d37-ce75-4921-bac5-4871c180c967)

### Steps to Reproduce the Bug or Issue

Use Input component with errorMessage and isInvalid

### Expected behavior

The text of error should visible properly

### Operating System Version

Windows

### Browser

Chrome

**Comment by SirMajed** [comment]
I fixed this issue by giving custom classnames for the error message. I changed the color and the size of the hint or bottom label
In your <Input ... />
define the classNames

`<Input
          classNames={{
            errorMessage: "text-red-500 text-small",
          }}`

**Comment by milad-raza** [comment]
@SirMajed it's just changing the color, issue is still there.

**Comment by wingkwong** [comment]
I couldn't reproduce the issue. It looks fine on my side. Can you please provide a reproducible sandbox environment?

<img width="520" alt="image" src="https://github.com/user-attachments/assets/a3f0d7d9-7dd3-48e6-85d9-e936132c31bb">

**Comment by milad-raza** [comment]
https://codesandbox.io/p/github/milad-raza/next-js-boilerplate/main?import=true

@wingkwong 
here is the code sandbox
this is happening in dark mode

**Comment by wingkwong** [comment]
can you also share what you see on your side?

<img width="518" alt="image" src="https://github.com/user-attachments/assets/ec8e3778-335c-41c5-9e7e-d5b1ee00e99f">

**Comment by milad-raza** [comment]
@wingkwong 
![image](https://github.com/user-attachments/assets/a3615dc1-f8f0-4ec4-9631-b8ad3a8b524a)
![image](https://github.com/user-attachments/assets/9ad3036d-f5b0-4ed4-9ab5-87ddc8c37dd8)


I'm using chrome

**Comment by wingkwong** [comment]
Focusing. Also using chrome.

![image](https://github.com/user-attachments/assets/5b6c69e9-4682-4c30-8e1c-832755e4ec83)

**Comment by milad-raza** [comment]
IDK but the issue is happening on my side as I shared SS

**Comment by milad-raza** [comment]
https://www.awesomescreenshot.com/video/31495204?key=f16e9d08ab5b7b34f0e4cceb892c99fa

**Comment by wingkwong** [comment]
Can you try on other machines or browsers?

**Comment by wingkwong** [comment]
Closing due to inactivity + not able to reproduce
