### ISSUE TITLE
[BUG] - <Tooltip /> component causes Next.JS 14 to crash in `next dev`

### ISSUE THREAD

**Issue by gdbroman** [nextui-org/nextui#3744]
### NextUI Version

2.4.2

### Describe the bug

When hovering on a Tooltip in dev mode in Next.js (14.2.7) it causes the crash:
```
Error: Only two keyframes currently supported with spring and inertia animations. Trying to animate scale(0.85),scale(0.86182),scale(0.88541),scale(0.91045),scale(0.93264),scale(0.95066),scale(0.96457),scale(0.97493),scale(0.98248),scale(0.98787),scale(0.99167),scale(0.99432),scale(0.99615),scale(0.9974),scale(0.99825),scale(0.99883),scale(0.99922),scale(0.99948),scale(0.99966),scale(0.99977),scale(1)
```

It seems to be a `framer-motion` issue, because when setting `disableAnimation={true}` it doesn't cause the app to crash anymore.

### Steps to Reproduce the Bug or Issue

1. Start Next.js app with `next dev`
2. Hover <Tooltip />
3. Next.js app crashes (see screenshot)

### Expected behavior

As a user I expect `<Tooltip />` to work in `next dev`

### Screenshots or Videos

![CleanShot 2024-09-12 at 19 01 15@2x](https://github.com/user-attachments/assets/9b19b563-cf59-4b7f-9228-d35411d4470c)

### Operating System Version

macOS 14.6.1

### Browser

Chrome

**Comment by wingkwong** [comment]
This has been resolved in previous version (after 2.4.2). Please upgrade to the latest version.

**Comment by gdbroman** [comment]
> This has been resolved in previous version (after 2.4.2). Please upgrade to the latest version.

Thanks for the answer @wingkwong! I just upgraded to `2.4.6` and while the issue seems to be less frequent I'm still getting this crash when quickly hovering over a Tooltip 2-3 times:

```
Error: Only two keyframes currently supported with spring and inertia animations. Trying to animate scale(0.85),scale(0.86182),scale(0.88541),scale(0.91045),scale(0.93264),scale(0.95066),scale(0.96457),scale(0.97493),scale(0.98248),scale(0.98787),scale(0.99167),scale(0.99432),scale(0.99615),scale(0.9974),scale(0.99825),scale(0.99883),scale(0.99922),scale(0.99948),scale(0.99966),scale(0.99977),scale(1)
```

**Comment by wingkwong** [comment]
Please check the docs. I think you also need to upgrade framer motion as well

**Comment by gdbroman** [comment]
That solved it! Thanks @wingkwong!

For anyone with the same problem: I upgraded framer-motion `11.0.8` -> `11.5.4`
