### ISSUE TITLE
[BUG] - Using CLI init creates a broken project

### ISSUE THREAD

**Issue by Thundernerd** [nextui-org/nextui#4453]
### NextUI Version

2.4.3

### Describe the bug

Using `npx nextui-cli@latest init` (and following the subsequent steps) results in a broken project.

The error is as follows:
```
 ✓ Ready in 638ms
 ○ Compiling / ...
 ✓ Compiled / in 2.2s
 ⨯ ./styles/globals.css
Error evaluating Node.js code
ReferenceError: module is not defined
    [at file:///workspaces/app/next-app-template/tailwind.config.js:4:1]
    [at ModuleJobSync.runSync (node:internal/modules/esm/module_job:395:35)]
    [at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:329:47)]
    [at loadESMFromCJS (node:internal/modules/cjs/loader:1414:24)]
    [at Module._compile (node:internal/modules/cjs/loader:1547:5)]
    [at Object..js (node:internal/modules/cjs/loader:1708:10)]
    [at Module.load (node:internal/modules/cjs/loader:1318:32)]
    [at Function._load (node:internal/modules/cjs/loader:1128:12)]
    [at TracingChannel.traceSync (node:diagnostics_channel:322:14)]
    [at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)]
```

### Steps to Reproduce the Bug or Issue

1. Make sure you have a devcontainer setup with nodejs and typescript (the image I used is `mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm`)
2. Run `npx nextui-cli@latest init`
3. Select the App template
4. Enter any name
5. Use the NPM package manager
6. `cd` into your new project's directory
7. run `npm install`
8. run `npm run dev`
9. Notice the error

### Expected behavior

As a user, I expected _a working project_ behavior but I am seeing
```
 ⨯ ./styles/globals.css
Error evaluating Node.js code
ReferenceError: module is not defined
    [at file:///workspaces/app/next-app-template/tailwind.config.js:4:1]
```

### Operating System Version

Linux

### Browser

Chrome

**Comment by ibrahimmudassar** [comment]
I have this same problem running it on vercel using the same cli. runs and builds fine on windows but does not run on vercel. This is a completely empty project made with the cli and then deployed with vercel. same version

![image](https://github.com/user-attachments/assets/a9bff182-1250-4d79-bd6a-28c74e251afa)

**Comment by winchesHe** [comment]
Could you try using this [app template](https://github.com/nextui-org/next-app-template) directly and verify if there are any errors? It doesn't seem to be a CLI issue since its only task is to pull the template to your local machine and guide you through running it,

Or could you provide a minimal reproduction on codesandbox/stackblitz? I haven't been able to reproduce this issue locally.

**Comment by ibrahimmudassar** [comment]
just tried the app template on vercel and it has the same error. When I build it locally I don't have any problems though. I can't reproduce this on my own machine.

**Comment by winchesHe** [comment]
@wingkwong Have you encountered any issues with app-template build failures on Vercel

**Comment by wingkwong** [comment]
@winchesHe seems something went wrong with this [commit](https://github.com/nextui-org/next-app-template/commit/ee0f50754fd242d299558629e010e4fce8c56e02). I'll handle it.

**Comment by wingkwong** [comment]
Fixed the dependencies. Please run init again to create a new project or update the versions following [package.json](https://github.com/nextui-org/next-app-template/blob/main/package.json)

<img width="1455" alt="image" src="https://github.com/user-attachments/assets/a7dc000c-03d2-4125-89cd-504c2b1da052" />

**Comment by isaacboentoro** [comment]
This issue persists for me using `npx nextui-cli@latest init`

**Comment by Thundernerd** [comment]
> Could you try using this [app template](https://github.com/nextui-org/next-app-template) directly and verify if there are any errors? It doesn't seem to be a CLI issue since its only task is to pull the template to your local machine and guide you through running it,
> 
> Or could you provide a minimal reproduction on codesandbox/stackblitz? I haven't been able to reproduce this issue locally.

Using the app template manually still results in the same error.

I'm unable to figure out codesandbox and stackblitz. My setup uses a devcontainer which is a minimal environment. Maybe the cause lies in the fact that it is a minimal environment and there is a hidden missing dependency or something like that.

**Comment by Thundernerd** [comment]
Issue definitely still persists for me on all the latest versions.

**Comment by wingkwong** [comment]
@isaacboentoro @Thundernerd I couldn't reproduce the issue locally & on vercel so I think the error may be caused from devcontainer. Are you also using `typescript-node:1-22-bookworm`? Can you try an image that is using node 20 and test again? If module is still not supported, then you may need to apply the fix mentioned [here](https://github.com/nextui-org/nextui/issues/4453#issuecomment-2565125590).

**Comment by Thundernerd** [comment]
@wingkwong can confirm that using node 20 works :)

**Comment by isaacboentoro** [comment]
> @isaacboentoro @Thundernerd I couldn't reproduce the issue locally & on vercel so I think the error may be caused from devcontainer. Are you also using `typescript-node:1-22-bookworm`? Can you try an image that is using node 20 and test again? If module is still not supported, then you may need to apply the fix mentioned [here](https://github.com/nextui-org/nextui/issues/4453#issuecomment-2565125590).

Can confirm that the fix mentioned worked.

**Comment by marefati110** [comment]
i have same issue
